### ISSUE TITLE
IndexOutOfRangeException thrown when generating character 186 (║)

### ISSUE THREAD

**Issue by nightblade9** [SadConsole/SadConsole#215]
In my game, I'm rendering the double-pipe character (`║`) in some situations. Whenever I try to draw something with this character, I get an `IndexOutOfRangeException`. Here's the stack:

```
Exception has occurred: CLR/System.IndexOutOfRangeException
An unhandled exception of type 'System.IndexOutOfRangeException' occurred in SadConsole.dll: 'Index was outside the bounds of the array.'
   at SadConsole.Renderers.Basic.RenderCells(SurfaceBase surface, Boolean force)
   at SadConsole.Renderers.Basic.Render(SurfaceBase surface, Boolean force)
   at SadConsole.Surfaces.SurfaceBase.Draw(TimeSpan timeElapsed)
   at SadConsole.ScreenObject.Draw(TimeSpan timeElapsed)
   at SadConsole.Game.SadConsoleGameComponent.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at DeenGames.AliTheAndroid.Program.Main() in D:\code\ali-the-android\AliTheAndroid\Program.cs:line 37
```

According to `Program.cs`, I'm using the IBM font:

`SadConsole.Game.Create("Fonts/IBM.font", GameWidthInTiles, GameHeightInTiles);`

The containts of said `IBM.font` file are:

`{"FilePath":"IBM8x16.png","GlyphHeight":16,"GlyphPadding":1,"GlyphWidth":8,"Name":"IBM","SolidGlyphIndex":219}`

The image is the usual one that ships with SadConsole games. I've uploaded it here for your perusal:

![](https://github.com/deengames/ali-the-android/raw/master/AliTheAndroid/Fonts/IBM8x16.png)

You can see the character exists in the image (12th row, near the end).  

How do I get this to work / what am I doing wrong?

If you so wish, you can see all my code here: https://github.com/deengames/ali-the-android/tree/master/AliTheAndroid

**Comment by SadConsole** [comment]
I'm guessing you're typing in the character via a string or something (like ALT+KEYPAD)? you can't do that because it injects a unicode character into the string instead of the standard ascii character. SO the index it looks up is too high.

**Comment by nightblade9** [comment]
That's exactly what I'm doing. What's the right way to add the character?

**Comment by SadConsole** [comment]
well you can use string interpolation with the character number `$"Hello {'162'}"` but that isn't as pretty :) I haven't really learned how unicode characters are put together and how to translate them into pure ascii characters.

**Comment by nightblade9** [comment]
I found a simple work-around: `char to_display = (char)186;` this prints `║` as expected.

I will close this, since I am okay with this. I can always assign it to a constant, etc. if I want readability.
